yaml
name: Aviso Lotofácil

on:
  schedule:
    - cron: '0 20 * * *'  # Roda todo dia às 20h UTC (17h no Brasil, ajuste se quiser)
  workflow_dispatch:  # Permite executar manualmente também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Run Lotofacil script
      run: python lotofacil_alert.py
      env:
        TOKEN: secrets.TOKEN 
        CHAT_ID:{{ secrets.CHAT_ID }}
